# Let us create a simple example for Markov Reward Process

<img src='./mrp1.png' width=500px>

In [1]:
from mrp import MRP

# states
S = ['s0', 's1', 's2', 's3', 'T']


# Probability transition
P = [[0, 0.3, 0.3, 0.4, 0],
     [0, 0, 0, 1.0, 0],           
     [0, 0.5, 0, 0, 0.5],
     [0, 0, 0, 0, 1.0],
     [0, 0, 0, 0, 1.0]]

# rewards
R = [-1, -1, -1, -1, 0]

mrp = MRP(S, P, R)

In [8]:
# lets create some sample trajectories / episodes 
import pandas as pd
pd.set_option('display.max_colwidth',-1)
episodes = [mrp.generate_episodes() for i in range(50)]
episodes_df = pd.Series(episodes).to_frame()
episodes_df['length'] = episodes_df[0].apply(len)
episodes_df

                                                          0  length
0   [(s1, -1, s3), (s3, -1, T)]                              2
1   [(s1, -1, s3), (s3, -1, T)]                              2
2   [(s0, -1, s3), (s3, -1, T)]                              2
3   [(s2, -1, s1), (s1, -1, s3), (s3, -1, T)]                3
4   [(s2, -1, s1), (s1, -1, s3), (s3, -1, T)]                3
5   [(s1, -1, s3), (s3, -1, T)]                              2
6   [(s1, -1, s3), (s3, -1, T)]                              2
7   [(s1, -1, s3), (s3, -1, T)]                              2
8   [(s3, -1, T)]                                            1
9   [(s2, -1, T)]                                            1
10  [(s0, -1, s1), (s1, -1, s3), (s3, -1, T)]                3
11  [(s2, -1, s1), (s1, -1, s3), (s3, -1, T)]                3
12  [(s3, -1, T)]                                            1
13  [(s3, -1, T)]                                            1
14  [(s3, -1, T)]                                            1
15  [(s2, -1, s1), (s1, -1, s3), (s3, -1, T)]                3
16  [(s3, -1, T)]                                            1
17  [(s1, -1, s3), (s3, -1, T)]                              2
18  [(s3, -1, T)]                                            1
19  [(s2, -1, s1), (s1, -1, s3), (s3, -1, T)]                3
20  [(s2, -1, s1), (s1, -1, s3), (s3, -1, T)]                3
21  [(s2, -1, s1), (s1, -1, s3), (s3, -1, T)]                3
22  [(s0, -1, s3), (s3, -1, T)]                              2
23  [(s0, -1, s2), (s2, -1, s1), (s1, -1, s3), (s3, -1, T)]  4
24  [(s2, -1, T)]                                            1
25  [(s0, -1, s1), (s1, -1, s3), (s3, -1, T)]                3
26  [(s2, -1, T)]                                            1
27  [(s1, -1, s3), (s3, -1, T)]                              2
28  [(s1, -1, s3), (s3, -1, T)]                              2
29  [(s0, -1, s3), (s3, -1, T)]                              2
30  [(s2, -1, s1), (s1, -1, s3), (s3, -1, T)]                3
31  [(s1, -1, s3), (s3, -1, T)]                              2
32  [(s3, -1, T)]                                            1
33  [(s0, -1, s3), (s3, -1, T)]                              2
34  [(s1, -1, s3), (s3, -1, T)]                              2
35  [(s0, -1, s3), (s3, -1, T)]                              2
36  [(s3, -1, T)]                                            1
37  [(s0, -1, s3), (s3, -1, T)]                              2
38  [(s2, -1, s1), (s1, -1, s3), (s3, -1, T)]                3
39  [(s2, -1, T)]                                            1
40  [(s3, -1, T)]                                            1
41  [(s3, -1, T)]                                            1
42  [(s3, -1, T)]                                            1
43  [(s2, -1, T)]                                            1
44  [(s3, -1, T)]                                            1
45  [(s3, -1, T)]                                            1
46  [(s3, -1, T)]                                            1
47  [(s1, -1, s3), (s3, -1, T)]                              2
48  [(s1, -1, s3), (s3, -1, T)]                              2
49  [(s0, -1, s3), (s3, -1, T)]                              2